baseURL = "https://vvasuki.github.io/rahaShTippaNayaH/"
languageCode = "en-us"
title = "रहष्टिप्पणयः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true
[params]
  githubEditMePathBase = "https://github.com/vvasuki/rahaShTippaNayaH/edit/master/content/"
  contactLink = "https://github.com/vvasuki/rahaShTippaNayaH/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"
